# Configurações básicas
title: "Mad Mage Dungeon"
description: "Um site incrível hospedado no GitHub Pages"
baseurl: "./" # O subdiretório do seu site (nome do repositório)
url: "https://rpg.williambarros.com.br" # A URL do seu site

# Informações do autor
author:
  name: "William Barros"
  email: "mad.mage.rpg@gmail.com"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "pt"
# Outros detalhes
permalink: /blog/:year/:month/:title
language: pt
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-tagging-related_posts
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: /blog/feed.atom
  
# Compress HTML
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
